project_id = "ostwawzkkkrreoygkhji"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.generate-reply]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false